# Generated by Django 5.1.4 on 2025-01-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_room_amenities_remove_room_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_id',
            new_name='serial_number',
        ),
    ]
