# Generated by Django 5.1.4 on 2025-01-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_reservation_id_reservation_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='serial_number',
            new_name='reservation_id',
        ),
    ]
